### PR TITLE
Add more instructions for OSX

### PR DESCRIPTION
**Pull request by ironcladlou**
Add a couple of troubleshooting instructions for OSX users.

### CODE REVIEW

**Comment by ironcladlou** [comment]
These steps could use more independent verification.

**Comment by pnasrat** [comment]
Binary file dlv accidentaly added?

**Comment by ironcladlou** [comment]
@pnasrat 
>Binary file dlv accidentaly added?

Oops, fixed. Thanks!

**Comment by derekparker** [comment]
Thanks!

**Pull request merged**
