### PR TITLE
Add "l" alias for list command

### PR DESCRIPTION
**Pull request by whit537**
This would help out those of us habituated to [pdb](https://docs.python.org/3/library/pdb.html). 😊

### CODE REVIEW

**Comment by whit537** [comment]
Pdb inherits this behavior from [GDB](https://sourceware.org/gdb/current/onlinedocs/gdb/List.html#List), fwiw. Also, in both cases, additional `(l)ist` commands page further through the source code rather than relisting the same code snippet multiple times. Supporting that in Delve would take a bigger diff, though. ;)

**Comment by whit537** [comment]
No apology necessary! Open source is voluntary! :)

Travis > Linux builds could use a restart? Timed out ...

**Comment by derekparker** [comment]
>Travis > Linux builds could use a restart? Timed out ...

Yeah that's been happening on other PRs too, investigating now.

**Comment by whit537** [comment]
> Yeah that's been happening on other PRs too, investigating now.

If chronic might deserve a ticket of its own?

**Comment by derekparker** [comment]
Travis seems to be having a hard time with the Linux builds, tested locally and merged. Thanks!

**Pull request merged**
