### PR TITLE
dlv: Flag to print stacktrace on trace subcommand

### PR DESCRIPTION
**Pull request by derekparker**

### CODE REVIEW

**Comment by aarzilli** [comment]
LGTM. I just wanted to mention that the trace subcommand should probably be implemented by setting the `Tracepoint` flag and then just calling `terminal.cont`.

**Comment by derekparker** [comment]
>  I just wanted to mention that the trace subcommand should probably be implemented by setting the Tracepoint flag and then just calling terminal.cont.

Good call, I'll refactor this.

**Comment by derekparker** [comment]
@aarzilli refactored.

**Comment by aarzilli** [comment]
Merged with 8a1f36a1ce71d708d1d82afbc2191de9aefba021

**Pull request closed without merging**
