### PR TITLE
Added documentation about flag support with --

### PR DESCRIPTION
**Pull request by njason**
I only find it mentioned in #126

### CODE REVIEW

**Comment by derekparker** [comment]
Thanks for this patch, however the file you've modified is auto-generated. Can you update the internal help output at `cmd/dlv/cmds/commands.go` and regenerate the documentation via `go run ./scripts/gen-cli-docs.go` and `go run ./scripts/gen-usage-docs.go`.

**Comment by njason** [comment]
@derekparker Updated commands.go, thanks for the instructions.

**Comment by derekparker** [comment]
@njason thanks! Can you squash and rebase and I'll merge.

**Comment by njason** [comment]
@derekparker I somehow closed this PR. The squashed one is here https://github.com/derekparker/delve/pull/740

**Pull request closed without merging**
