### PR TITLE
build: Add git sha to version output

### PR DESCRIPTION
**Pull request by derekparker**

### CODE REVIEW

**Comment by derekparker** [comment]
Ping @aarzilli for review.

**Comment by aarzilli** [comment]
Good idea, I was thinking of doing something similar (but with go generate) recently.

**Comment by derekparker** [comment]
@aarzilli agree with your comment, pushed new change.

**Comment by aarzilli** [comment]
Merged with 0abc772023bcde7f84a1094787e608220f9d8c0f

**Pull request closed without merging**
