### PR TITLE
Allow using list command with frame

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by icholy** [comment]
@aarzilli should I be doing that instead?

**Comment by aarzilli** [comment]
Not necessarily, I was just making the alternative known.

**Comment by icholy** [comment]
@derekparker thoughts?

**Comment by derekparker** [comment]
I'm fine with this approach. Merged.

The only concern I have is not with this patch, but with this code path in general. We're specifically white listing certain commands here, which could be aliased in other ways, specifically through configuration. Any user defined aliases for these commands would then not work. I haven't put much thought into a better solution so I'm open to ideas.

**Comment by aarzilli** [comment]
>The only concern I have is not with this patch, but with this code path in general

We could have every command function get a context object as the first argument and stick EvalScope inside that.

**Pull request closed without merging**
