### PR TITLE
Loading breakpoints/tracepoints from a file

### PR DESCRIPTION
**Pull request by aarzilli**
It's implemented on top of the continue-bug branch that I already have a PR open for, I will rebase it as needed.

### CODE REVIEW

**Comment by derekparker** [comment]
I'll have a chance to review this weekend.

**Comment by derekparker** [comment]
Can you rebase this on master.

**Comment by aarzilli** [comment]
rebased

**Comment by derekparker** [comment]
I'm not sold on continuing to watch the file for changes after the debugger has started. Seems like we should just parse that file on startup, add the breakpoints / tracepoints and then go about our way.

**Comment by aarzilli** [comment]
I like to be able to change or add a breakpoint in a single place, instead of having to give a command to delve and then manually update the file.

**Comment by derekparker** [comment]
I wonder how common of a use case that is, and whether it's worth complicating the code with file system notifications. @pmorie you had created the original issue of setting breakpoints from a file, would you mind chiming in on this? Essentially whether it's beneficial enough from a users perspective to have Delve watch the input breakpoint file for changes, and then apply those changes (i.e. add breakpoints / tracepoints).

**Comment by derekparker** [comment]
Two things:

1) Can you separate the watch stuff from the initial "read breakpoints from file" patch.
2) I think a more general "source" type command (for evaluating the breakpoint file) would be cool. Because essentially, the breakpoint file is a newline delimited list of valid Delve commands. Delve should be able to essentially source a file and have it take effect.

**Comment by derekparker** [comment]
Lastly, could you rework the commit message to conform to: https://github.com/derekparker/delve/blob/master/CONTRIBUTING.md#format-of-the-commit-message

**Comment by pmorie** [comment]
I will TAL in the next couple days

**Comment by aarzilli** [comment]
Done. A file that can contain any command is not a 'breakpoints file' however, so I have renamed it to 'init file'.

But now that we have config files I wonder if it wouldn't be better to add a flag to specify a config file and move the breakpoints/tracepoints inside the configuration?

**Comment by derekparker** [comment]
I think this is really good, however there is one issue. When executing `dlv debug --init="./commands.txt" --headless` the init file is ignored because we do not start a terminal in headless mode. How about we attach the InitFile to the server instead, and let the server have access to the commands so it can call `cmds.executeFile`, while still preserving the `source` command in the terminal.

That way this init file will be executed even in headless mode, and allows us to have a generic "startup file" that is sourced immediately on startup by default, and that would work in headless mode as well.

We could even move the command code into its own package, and away from the terminal package. That would make this a bit cleaner, I think.

Thoughts?

**Comment by aarzilli** [comment]
It seems like a lot of trouble without much of a use case at the moment: where's the output from commands executed by the headless server going to go? What happens if the init script ends with a `continue` command? Are client going to start by issuing a `Halt` call? How are they going to know when the `Halt` has taken effect? If someone writes a different client why should the init file still be in this command language?

**Comment by derekparker** [comment]
@aarzilli good points. Let's just provide information in the doc string for the flag that it will not take effect if Delve is run in headless mode.

**Comment by pmorie** [comment]
@derekparker Apologies, I have been in dire straights getting some stuff sorted for Kubernetes 1.1 and OpenShift 3.1.  Still trying to find time to review this.

**Comment by aarzilli** [comment]
done.

**Comment by derekparker** [comment]
@aarzilli please rebase and I will merge.

**Comment by aarzilli** [comment]
rebased

**Comment by pmorie** [comment]
I haven't had a chance to review the code, but this LGTM from the standpoint of how I was expecting to use the feature.

**Comment by derekparker** [comment]
Merged.

**Comment by aarzilli** [comment]
I know you don't like the idea of automatically reloading on change with inotify, but I find it useful, if you end up changing your mind I'm keeping my changes [here](https://github.com/aarzilli/delve/tree/initfile-autoreload).

**Comment by pmorie** [comment]
One issue w/ using inotify is that you can run out of events.

**Comment by aarzilli** [comment]
@pmorie You mean running out of watches or you mean the event queue overflowing? Neither seems like a problem for this application. Is there some other issue I'm not aware of?

**Comment by pmorie** [comment]
I was referring to running out of watches.  I don't think it will be a
problem for short-running sessions but I know of use-cases where people ran
something in a debugger for longer than you would expect, hoping to
recreate a bug, so I just thought I would mention it.

On Tue, Oct 6, 2015 at 2:14 PM, Alessandro Arzilli <notifications@github.com

**Comment by aarzilli** [comment]
I see.

**Pull request closed without merging**
