### PR TITLE
proc/variables: mark malformed maps as unreadable instead of panicking

### LINKED ISSUE #685: panic: interface conversion: dwarf.Type is *dwarf.VoidType, not *dwarf.StructType
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 0.11.0-alpha
Build: v0.11.0
2. What version of Go are you using? (`go version`)?
1.7.3
3. What operating system and processor architecture are you using?
mac os 10.12.1
4. What did you do?
goland IDE run Debugger & http POST /api/rpm/pricing/lnbase/

runtime: no module data for 0x0
fatal error: no module data
[tango] 2016/12/16 15:28:07 [Debug] logger.go:51 Started POST /api/rpm/pricing/lnbase/ for 172.168.173.5
panic: interface conversion: dwarf.Type is *dwarf.VoidType, not *dwarf.StructType

goroutine 9 [running]:
panic(0x44aab20, 0xc42251a040)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/go/src/runtime/panic.go:500 +0x1a1
github.com/derekparker/delve/proc.mapEvacuated(0xc4235beb60, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:1379 +0x180
github.com/derekparker/delve/proc.(*mapIterator).nextBucket(0xc4231d4120, 0x8)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:1269 +0xa17
github.com/derekparker/delve/proc.(*mapIterator).next(0xc4231d4120, 0xc4231d4120)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:1346 +0x49
github.com/derekparker/delve/proc.(*Variable).loadMap(0xc4234e41b0, 0x1, 0x1, 0x1, 0x40, 0x40, 0xffffffffffffffff)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:1159 +0x13b
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc4234e41b0, 0x1, 0x1, 0x1, 0x40, 0x40, 0xffffffffffffffff)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:757 +0xa02
github.com/derekparker/delve/proc.(*Variable).loadValueInternal(0xc4235c6b60, 0x0, 0x1, 0x1, 0x40, 0x40, 0xffffffffffffffff)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:783 +0x3a2
github.com/derekparker/delve/proc.(*Variable).loadValue(0xc4235c6b60, 0x1, 0x1, 0x40, 0x40, 0xffffffffffffffff)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:726 +0x5b
github.com/derekparker/delve/proc.(*EvalScope).extractVariableFromEntry(0xc423055cc0, 0xc42073af00, 0x1, 0x1, 0x40, 0x40, 0xffffffffffffffff, 0xc4235c9180, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:505 +0x9a
github.com/derekparker/delve/proc.(*EvalScope).variablesByTag(0xc423055cc0, 0x34, 0x1, 0x1, 0x40, 0x40, 0xffffffffffffffff, 0x4011378, 0x20, 0x44d45e0, ...)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:1561 +0x14c
github.com/derekparker/delve/proc.(*EvalScope).LocalVariables(0xc423055cc0, 0x1, 0x1, 0x40, 0x40, 0xffffffffffffffff, 0x41e20a2, 0x0, 0x0, 0x0, ...)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/proc/variables.go:536 +0x61
github.com/derekparker/delve/service/debugger.(*Debugger).convertStacktrace(0xc420134480, 0xc4200dcd80, 0xb, 0xb, 0xc42398b8f8, 0x0, 0x0, 0xc423081960, 0xc41ffceac9, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:739 +0x42c
github.com/derekparker/delve/service/debugger.(*Debugger).Stacktrace(0xc420134480, 0xffffffffffffffff, 0xa, 0xc42398b8f8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:729 +0x189
github.com/derekparker/delve/service/rpc2.(*RPCServer).Stacktrace(0xc420731ba0, 0xffffffffffffffff, 0xa, 0x1, 0x0, 0xc423055b20, 0x0, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/rpc2/server.go:143 +0xda
reflect.Value.call(0xc4231e4900, 0xc420132528, 0x13, 0x4527ff9, 0x4, 0xc42398bf10, 0x3, 0x3, 0xc423055b20, 0x0, ...)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc4231e4900, 0xc420132528, 0x13, 0xc42398bf10, 0x3, 0x3, 0x3, 0x3, 0x0)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/go/src/reflect/value.go:302 +0xa4
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec(0xc420130410, 0x5ea0678, 0xc420140010)
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/rpccommon/server.go:288 +0x68f
created by github.com/derekparker/delve/service/rpccommon.(*ServerImpl).Run.func1
	/Users/builduser/buildAgent/work/b97f8195591f35ac/gopath/src/github.com/derekparker/delve/service/rpccommon/server.go:146 +0xdc

Process finished with exit code 2

### PR DESCRIPTION
**Pull request by aarzilli**
```
proc/variables: mark malformed maps as unreadable instead of panicking

Under currently undetermined circumstances we encounter a map type that
has a malformed buckets, oldbuckets or overflow field.
Check the type of buckets, oldbuckets and overflow before using them.

Fixes #685

```

### CODE REVIEW

**Comment by derekparker** [comment]
Might be an alright workaround for the time being, but I'm hesitant to merge anything without understanding the root cause. 

Maybe we can get some core team to chime in? @randall77 (not sure if you're the person to reach out to, but maybe to can shed some light or ping someone who could?)

**Comment by randall77** [comment]
I'm the right person for this.  What is the problem, exactly?  Where are you getting the map type from, and how exactly is it malformed?

**Comment by aarzilli** [comment]
Issue #685 has attached the output of `objdump --dwarf` for a program causing this. Judging by the stack trace it would be either a buckets or oldbuckets entry marked as unsafe.Pointer instead of its struct type.

But I couldn't figure out how that could happen.

**Comment by randall77** [comment]
Possibly this could be due to the optimization that if the key and value are both pointer-free, then the overflow pointers are encoded differently.  They would be uintptrs that are offsets into hmap.overflow.
If you tried to dereference an overflow pointer that was actually an index, that might make this happen?

**Comment by aarzilli** [comment]
@randall77 you mean the overflow field of bmap? Yes that could cause this problem. Is there an easy way to make a map with overflow buckets to test this?

**Comment by randall77** [comment]
@aarzilli Yes, make a map[int]int and put 800 entries in it.  With high probability you'll get at least one overflow bucket.

**Comment by aarzilli** [comment]
So I wrote this test: [it's here](https://github.com/aarzilli/delve/commit/497983ab3da4e94ebee8e45e91ae645bf391e2d5).

The map definitely has overflow but the test passes, in debug_info I have:

```
 <1><1b0fd>: Abbrev Number: 16 (DW_TAG_typedef)
    <1b0fe>   DW_AT_name        : map[int]int
    <1b10a>   DW_AT_type        : <0x1fd77>
    <1b112>   Unknown AT value: 2900: 21
    <1b113>   Unknown AT value: 2901: <0x16b89>
    <1b11b>   Unknown AT value: 2902: <0x16b89>

 <1><1fd77>: Abbrev Number: 17 (DW_TAG_pointer_type)
    <1fd78>   DW_AT_name        : *hash<int,int>
    <1fd87>   DW_AT_type        : <0x1fccb>
    <1fd8f>   Unknown AT value: 2900: 0

 <1><1fccb>: Abbrev Number: 21 (DW_TAG_structure_type)
    <1fccc>   DW_AT_name        : hash<int,int>
    <1fcda>   DW_AT_byte_size   : 48
    <1fcdb>   Unknown AT value: 2900: 0
...
 <2><1fd20>: Abbrev Number: 6 (DW_TAG_member)
    <1fd21>   DW_AT_name        : buckets
    <1fd29>   DW_AT_data_member_location: 2 byte block: 23 10   (DW_OP_plus_uconst: 16)
    <1fd2c>   DW_AT_type        : <0x1fcb0>
 <2><1fd34>: Abbrev Number: 6 (DW_TAG_member)
    <1fd35>   DW_AT_name        : oldbuckets
    <1fd40>   DW_AT_data_member_location: 2 byte block: 23 18   (DW_OP_plus_uconst: 24)
    <1fd43>   DW_AT_type        : <0x1fcb0>
...
 <2><1fd76>: Abbrev Number: 0

 <1><1fcb0>: Abbrev Number: 17 (DW_TAG_pointer_type)
    <1fcb1>   DW_AT_name        : *bucket<int,int>
    <1fcc2>   DW_AT_type        : <0x1fc4d>
    <1fcca>   Unknown AT value: 2900: 0

 <1><1fc4d>: Abbrev Number: 21 (DW_TAG_structure_type)
    <1fc4e>   DW_AT_name        : bucket<int,int>
    <1fc5e>   DW_AT_byte_size   : 144
    <1fc60>   Unknown AT value: 2900: 0
 <2><1fc61>: Abbrev Number: 6 (DW_TAG_member)
    <1fc62>   DW_AT_name        : tophash
    <1fc6a>   DW_AT_data_member_location: 2 byte block: 23 0    (DW_OP_plus_uconst: 0)
    <1fc6d>   DW_AT_type        : <0x1b90c>
 <2><1fc75>: Abbrev Number: 6 (DW_TAG_member)
    <1fc76>   DW_AT_name        : keys
    <1fc7b>   DW_AT_data_member_location: 2 byte block: 23 8    (DW_OP_plus_uconst: 8)
    <1fc7e>   DW_AT_type        : <0x1fc0b>
 <2><1fc86>: Abbrev Number: 6 (DW_TAG_member)
    <1fc87>   DW_AT_name        : values
    <1fc8e>   DW_AT_data_member_location: 2 byte block: 23 48   (DW_OP_plus_uconst: 72)
    <1fc91>   DW_AT_type        : <0x1fc2c>
 <2><1fc99>: Abbrev Number: 6 (DW_TAG_member)
    <1fc9a>   DW_AT_name        : overflow
    <1fca3>   DW_AT_data_member_location: 3 byte block: 23 88 1         (DW_OP_plus_uconst: 136)
    <1fca7>   DW_AT_type        : <0x1fcb0>
 <2><1fcaf>: Abbrev Number: 0

```

Note how overflow in `bucket<int, int>` has type `*bucket<int, int>`. So where's the overflow fields that aren't pointers? I'm confused. This is with 1.7.4, the bug was reported on 1.7.3 but I doubt hmap changed between implementations.
@randall77

**Comment by randall77** [comment]
Never mind about the index thing, I'm confused.  They are indeed pointers.  It is just that the garbage collector doesn't know that they are pointers.  It looks like the dwarf info is correct.

You can read about how the hidden pointers work in runtime/hashmap.go:117-125 and cmd/compile/internal/gc/reflect.go:140-146.

So back to the original problem, I'm not sure what is going on.
Any chance the malformed bucket is allocated on the stack?  I could see a bucket containing junk before it was initialized in that situation.

**Comment by aarzilli** [comment]
@randall77
> Any chance the malformed bucket is allocated on the stack? I could see a bucket containing junk before it was initialized in that situation.

The problem is in debug_info, not in the contents of the map. I wrote a parser for objdump format and dug through the output posted by @d4rkstar and finally I found it:

```
 <1><131e57>: Numero dell'abbreviazione: 21 (DW_TAG_typedef)
    <131e58>   DW_AT_name        : (stringa indiretta, offset: 0x87399): map[string]string
    <131e5c>   DW_AT_type        : <0x16a839>
    <131e64>   Valore AT sconosciuto: 2900: 21
    <131e65>   Valore AT sconosciuto: 2901: <0x12e7ad>
    <131e6d>   Valore AT sconosciuto: 2902: <0x12e7ad>

 <1><16a839>: Numero dell'abbreviazione: 14 (DW_TAG_pointer_type)
    <16a83a>   DW_AT_name        : (stringa indiretta, offset: 0xbf8cc): *hash<string,string>
    <16a83e>   DW_AT_type        : <0x16a7b1>
    <16a846>   Valore AT sconosciuto: 2900: 0

 <1><16a7b1>: Numero dell'abbreviazione: 11 (DW_TAG_structure_type)
    <16a7b2>   DW_AT_name        : (stringa indiretta, offset: 0xbf8b8): hash<string,string>
    <16a7b6>   DW_AT_byte_size   : 48
    <16a7b7>   Valore AT sconosciuto: 2900: 0
...
 <2><16a7f8>: Numero dell'abbreviazione: 12 (DW_TAG_member)
    <16a7f9>   DW_AT_name        : (stringa indiretta, offset: 0x8dd): buckets
    <16a7fd>   DW_AT_data_member_location: blocco da 2 byte: 23 10      (DW_OP_plus_uconst: 16)
    <16a800>   DW_AT_type        : <0x16a7ab>
...

 <1><16a7ab>: Numero dell'abbreviazione: 27 (DW_TAG_pointer_type)
    <16a7ac>   DW_AT_name        : (stringa indiretta, offset: 0xbf8a1): *bucket<string,string>
    <16a7b0>   Valore AT sconosciuto: 2900: 0
```

Note how `*bucket<string,string>` doesn't have a DW_AT_type and therefore is interpreted as a void pointer. If you look at the output posted on the issue you will also see that the entry for `bucket<string,string>` does exist, it's just that `*bucket<string,string>` doesn't reference it.
Of course just making a simple program that uses `map[string]string` does not replicate this bug.

Personally I think the macOS (sierra) system linker is doing nasty things to debug_info in some circumstances, for example here's a [reproducible example](https://github.com/golang/go/issues/17897)  of runtime.g being mangled in a similar way (closed because it can't be replicated in 1.8).

**Comment by aarzilli** [comment]
@derekparker my recommendation is that we merge this as mitigation, then if/when this problem gets reproduced against 1.8+ we report it to upstream.

**Comment by derekparker** [comment]
@aarzilli agreed.

**Pull request merged**
