### PR TITLE
Add basic tab completion to terminal

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by icholy** [comment]
@derekparker is there something wrong, or are the tests just flaky?

**Comment by derekparker** [comment]
Haven't had a chance to check CI as I'm currently driving cross country to
SF, however there is a flickering test on OSX I'm trying to fix. I will be
able to review your PRs this weekend.

**Comment by derekparker** [comment]
Merged, thanks!

**Comment by icholy** [comment]
When I have time, I want to extend it to complete variables, functions and file paths.

**Comment by derekparker** [comment]
@icholy that sounds good.

**Pull request closed without merging**
