### PR TITLE
doc/cli: fix clear-checkpoint command typo

### PR DESCRIPTION
**Pull request by iamzhout**

### CODE REVIEW

**Comment by aarzilli** [comment]
That file is autogenerated, this change needs to be done to pkg/terminal/command.go and then scripts/gen-cli-docs.go should be run.

**Comment by iamzhout** [comment]
@aarzilli thanks for info, I have fixed and updated the PR, please help to check.

**Comment by iamzhout** [comment]
I noticed the CI/appveyor/pr failed each time, seems that CI job will be killed if run longer than 10m?

```
*** Test killed: ran too long (10m0s).
FAIL	github.com/derekparker/delve/pkg/proc	600.070s
ok  	github.com/derekparker/delve/pkg/proc/core	0.025s
ok  	github.com/derekparker/delve/pkg/proc/gdbserial	0.913s
?   	github.com/derekparker/delve/pkg/proc/native	[no test files]
?   	github.com/derekparker/delve/pkg/proc/test	[no test files]
ok  	github.com/derekparker/delve/pkg/terminal	4.595s
?   	github.com/derekparker/delve/pkg/version	[no test files]
?   	github.com/derekparker/delve/service	[no test files]
?   	github.com/derekparker/delve/service/api	[no test files]
ok  	github.com/derekparker/delve/service/debugger	0.086s
?   	github.com/derekparker/delve/service/rpc1	[no test files]
?   	github.com/derekparker/delve/service/rpc2	[no test files]
?   	github.com/derekparker/delve/service/rpccommon	[no test files]
ok  	github.com/derekparker/delve/service/test	30.554s
?   	github.com/derekparker/delve/service/test/cmd	[no test files]
makefile:66: recipe for target 'test' failed
mingw32-make: *** [test] Error 1
Command exited with code 2
```

**Comment by aarzilli** [comment]
@iamzhout it's a problem with the windows backend, not your fault.

**Pull request merged**
