### PR TITLE
Implement regs command to print registers values, fixes #62

### LINKED ISSUE #62: Print contents of registers
Should be able to print contents of registers for current thread, and any other arbitrary thread.

### PR DESCRIPTION
**Pull request by dullgiulio**
Having some problems running the tests at the moment (on Linux and with go-tip). I will investigate further.

In the mean time you can have a look at this patch, if it does what is needed.

### CODE REVIEW

**Comment by derekparker** [comment]
Hey, thanks for this patch.

This is close, however we should print the contents of all the registers, not just the ones Delve cares about. On Linux, the generic Regs struct embeds the full system registers. We will want to do something similar on Darwin, and print the value of every register, using correct names (i.e. RIP instead of PC, etc..). Since this will be a relatively long list we'd want to newline delimit everything instead of comma separated.

**Comment by derekparker** [comment]
Also, I'm working through some fixes for getting Delve to work against go-tip. Should have some patches in this afternoon.

**Comment by dullgiulio** [comment]
Of course, I included all registers now.

I didn't use reflection: code is a bit redundant but explicit. Also, I don't have a Mac where I can try to build at the moment.

**Comment by derekparker** [comment]
Merged, thanks!

I fixed up a few things that we're broken on OSX, and also standardized the formatting a bit for Darwin vs Linux (register ordering mostly).

**Pull request closed without merging**
