### PR TITLE
[WIP] Read commands from file

### PR DESCRIPTION
**Pull request by epipho**
Also refactors command processing a bit to move the parsing of commands into the command package instead of cli.

Still untested but want to throw it up for comments.

### CODE REVIEW

**Comment by pnasrat** [comment]
FYI

I'm not sure how close #88 is to landing that would likely impact the command refactor part of this PR.

**Comment by epipho** [comment]
Since it looks like #88 is moving along, lets wait for that as it is much much larger than this change.  This one is easy to layer in on top later.

**Comment by derekparker** [comment]
@epipho same as other comment, #88 has been merged, so we can work on getting this PR merged in now.

**Comment by derekparker** [comment]
@epipho any chance you'd have some time to update this PR?

**Comment by epipho** [comment]
Crap I forgot about this one. I'll remerge it this weekend.

**Comment by derekparker** [comment]
@epipho I imagine you've been busy, but any chance you get rebase this PR so we can try getting it merged in?

**Comment by derekparker** [comment]
Going to kill this PR due to inactivity. If you happen to find time and would like to re-implement this on top of the current master, that would be great.

**Pull request closed without merging**
