### PR TITLE
Make info locals understand/print complex types

### LINKED ISSUE #192: Unknown type: *dwarf.ComplexType
```
~/src/gocode/bin/dlv --listen=localhost:9090 run m.go
127.0.0.1:9090
connected 127.0.0.1:9090
Type 'help' for list of commands.
(dlv) b m.go:5
Breakpoint 1 set at 0x2057 for main.main /Users/ignatov/src/gocode/src/delve_test/compl/m.go:5
(dlv) c
(+0.000000e+000+1.400000e+000i)
> main.main() /Users/ignatov/src/gocode/src/delve_test/compl/m.go:5

    0:	package main
    1:
    2:	func main() {
    3:		var z12 complex64 = 1.4i        ; println(z12)
    4:		var z13 complex128 = 1.0        ; println(z13)
=>  5:	}

(dlv) info locals
Unknown type: *dwarf.ComplexType
Unknown type: *dwarf.ComplexType
(dlv)
```

Mac OS X 10.10, go 1.4.2, the latest delve

### PR DESCRIPTION
**Pull request by ebfe**
Fixes #192

### CODE REVIEW

**Comment by derekparker** [comment]
Needs a test, otherwise looks good.

**Comment by ebfe** [comment]
done

**Comment by derekparker** [comment]
Breakpoint line must be updated to 59 in TestVariableFunctionScoping and TestLocalVariables.

**Comment by ebfe** [comment]
done. maybe for real this time :)

**Pull request merged**
