### PR TITLE
proc: implement detach on windows

### PR DESCRIPTION
**Pull request by alexbrainman**
This change is [Reviewable](https://reviewable.io/reviews/derekparker/delve/615)

### CODE REVIEW

**Comment by handicraftsman** [comment]
Now it crashes on windows, but runs on linux. Wow...

**Comment by handicraftsman** [comment]
Just end of test log in appveyor:
````
hi 7
hi 8
hi 8
FAIL
FAIL	github.com/derekparker/delve/proc	42.703s
?   	github.com/derekparker/delve/proc/test	[no test files]
?   	github.com/derekparker/delve/service	[no test files]
?   	github.com/derekparker/delve/service/api	[no test files]
ok  	github.com/derekparker/delve/service/debugger	0.078s
?   	github.com/derekparker/delve/service/rpc1	[no test files]
?   	github.com/derekparker/delve/service/rpc2	[no test files]
?   	github.com/derekparker/delve/service/rpccommon	[no test files]
ok  	github.com/derekparker/delve/service/test	46.656s
?   	github.com/derekparker/delve/service/test/cmd	[no test files]
ok  	github.com/derekparker/delve/terminal	3.813s
?   	github.com/derekparker/delve/version	[no test files]
makefile:65: recipe for target 'test' failed
mingw32-make: *** [test] Error 1
Command exited with code 2
````

**Comment by aarzilli** [comment]
@handicraftsman the test failures on windows should be fixed by #598

**Comment by aarzilli** [comment]
LGTM, surprised we don't have tests for Detach.

**Pull request merged**
