### PR TITLE
service/rpc: RPC server should serve requests consequently

### PR DESCRIPTION
**Pull request by zolotov**
`rpc.ServeCodec` runs all remote methods via go-routine. So it cannot give any guarantees about methods invokation order. As a result we have following bugs in IDEA<->Delve integration when breakpoints are set after `continue` command invokation: https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2360

This PR uses `ServeRequest` method instead, which is synchronously variant of serving request. 

Also I've run gofmt before commit, please tell me if you want to keep formatting changes in the separate commit.

### CODE REVIEW

**Comment by aarzilli** [comment]
The tests are failing. I suspect the problem is that with this change it's impossible to interrupt a running process.

**Comment by zolotov** [comment]
@aarzilli indeed, for example in Issue419 test `continue` method waits for some event from debugger. `halt` operation is supposed to lead to this event. Since all requests are synchronized, `halt` will be never started. 

I'm not sure if it's issue of test or production code and I have no enough knowledge of internal delve architecture to fix tests. So feel free to close this PR, in this case I'll just file an issue about race-condition due to requests invokation reordering.

**Comment by aarzilli** [comment]
It's not just the tests, a user can interrupt a running program by 
calling the halt command, if a continue command blocks further commands 
from being executed this doesn't work.

This patch needs a more complex approach.

**Comment by zolotov** [comment]
Filed an issue #523

**Comment by derekparker** [comment]
Closing this as we will likely take another approach.

**Pull request closed without merging**
