### PR TITLE
Fix for Issue #209

### PR DESCRIPTION
**Pull request by joegrasse**

### CODE REVIEW

**Comment by derekparker** [comment]
Thanks! Would you mind squashing your commits and amending the commit message to match https://github.com/derekparker/delve/blob/master/CONTRIBUTING.md#format-of-the-commit-message, please.

**Comment by joegrasse** [comment]
Done.

**Comment by derekparker** [comment]
I feel like we should detect the kernel version here. While technically both `t` and `T` are both considered "stop" statuses, they mean different things depending on the kernel version. For example, `T` is "stopped by job control signal" on modern kernels.

@aarzilli any thoughts on this?

**Comment by aarzilli** [comment]
IMHO that would only be useful if we were going to actually write support for job control signals. It seems like something that would take a lot of research for little payoff, I think it would only be relevant when we are attaching to a process running under a shell and the user is trying to control the process with the shell.  
Unless we are going to, there is no point in distinguishing them. I would merge the patch as is.

**Comment by derekparker** [comment]
Merged.

**Comment by derekparker** [comment]
@joegrasse thanks for the patch!

**Pull request closed without merging**
