### PR TITLE
proc: Crash when stepping past the end of the program [wip]

### LINKED ISSUE #414: panic: runtime error: invalid memory on step command
```
(dlv) s
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5ee57c]

goroutine 84 [running]:
github.com/derekparker/delve/proc.(*Thread).singleStep(0xc8205e9810, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/threads_linux.go:52 +0x1ac
github.com/derekparker/delve/proc.(*Thread).StepInstruction(0xc8205e9810, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/threads.go:96 +0x1a7
github.com/derekparker/delve/proc.(*Process).Step.func1(0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:481 +0x8f
github.com/derekparker/delve/proc.(*Process).run(0xc8207600e0, 0xc820055868, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:771 +0x12a
github.com/derekparker/delve/proc.(*Process).Step(0xc8207600e0, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:497 +0x53
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc82000ddc0, 0xc82050c100, 0x7fa286ae4000, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/service/debugger/debugger.go:284 +0x5a6
github.com/derekparker/delve/service/rpc.(*RPCServer).Command(0xc82000f6a0, 0xc82050c100, 0xc82050e0a0, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/server.go:107 +0x3f
reflect.Value.call(0x944f40, 0xa297c0, 0x13, 0xa47938, 0x4, 0xc820055ee8, 0x3, 0x3, 0x0, 0x0, ...)
	/usr/local/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x944f40, 0xa297c0, 0x13, 0xc820055ee8, 0x3, 0x3, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:300 +0xb1
net/rpc.(*service).call(0xc8204585c0, 0xc820458580, 0xc820491480, 0xc82008eb80, 0xc82048fc20, 0x878440, 0xc82050c100, 0x16, 0x8784a0, 0xc82050e0a0, ...)
	/usr/local/go/src/net/rpc/server.go:383 +0x1c1
created by net/rpc.(*Server).ServeCodec
	/usr/local/go/src/net/rpc/server.go:477 +0x4ac

goroutine 1 [chan receive]:
net/rpc.(*Client).Call(0xc820116120, 0xc82050c060, 0x11, 0x878440, 0xc82050c040, 0x8784a0, 0xc82050e000, 0x0, 0x0)
	/usr/local/go/src/net/rpc/client.go:315 +0xcd
github.com/derekparker/delve/service/rpc.(*RPCClient).call(0xc82010c200, 0xa47ae0, 0x7, 0x878440, 0xc82050c040, 0x8784a0, 0xc82050e000, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/client.go:254 +0xb4
github.com/derekparker/delve/service/rpc.(*RPCClient).Step(0xc82010c200, 0xb4f980, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/client.go:100 +0xcc
github.com/derekparker/delve/terminal.step(0xc82020ad70, 0x0, 0x0, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/terminal/command.go:467 +0x4c
github.com/derekparker/delve/terminal.(*Term).Run(0xc82020ad70, 0x0, 0x0, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/terminal/terminal.go:117 +0xab2
main.execute(0x0, 0xc82000d950, 0x1, 0x1, 0xc820026088, 0x0)
	/usr/src/go/src/github.com/derekparker/delve/cmd/dlv/main.go:362 +0x807
main.init.1.func4(0xc82011c800, 0xc82000d950, 0x1, 0x1)
	/usr/src/go/src/github.com/derekparker/delve/cmd/dlv/main.go:119 +0x4a
github.com/spf13/cobra.(*Command).execute(0xc82011c800, 0xc82000d8e0, 0x1, 0x1, 0x0, 0x0)
	/usr/src/go/src/github.com/spf13/cobra/command.go:569 +0x869
github.com/spf13/cobra.(*Command).ExecuteC(0xc82011c000, 0xc82011c800, 0x0, 0x0)
	/usr/src/go/src/github.com/spf13/cobra/command.go:656 +0x56b
github.com/spf13/cobra.(*Command).Execute(0xc82011c000, 0x0, 0x0)
	/usr/src/go/src/github.com/spf13/cobra/command.go:615 +0x2d
main.main()
	/usr/src/go/src/github.com/derekparker/delve/cmd/dlv/main.go:186 +0x3c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 19 [select, locked to thread]:
runtime.gopark(0xb502e0, 0xc820024728, 0xa4f0b0, 0x6, 0x430e18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820024728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820024728)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 55 [chan receive, locked to thread]:
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc8207600e0)
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:783 +0xc3
created by github.com/derekparker/delve/proc.New
	/usr/src/go/src/github.com/derekparker/delve/proc/proc.go:78 +0x1d4

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7fa2869395d8, 0x72, 0xc82000c1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820015a30, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820015a30, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200159d0, 0xc8204c4001, 0x5ff, 0x5ff, 0x0, 0x7fa286934050, 0xc82000c1b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026120, 0xc8204c4001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc82005dd40, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82005dd40, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc82005dd40, 0x966aa0, 0xc820493280, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc820493260, 0xc82010ca00, 0x0, 0x0)
	/usr/local/go/src/net/rpc/jsonrpc/server.go:66 +0x7c
net/rpc.(*Server).readRequestHeader(0xc820458580, 0x7fa286946530, 0xc820493260, 0x0, 0x0, 0xc82010ca00, 0xc820053c00, 0x0, 0x0)
	/usr/local/go/src/net/rpc/server.go:576 +0x90
net/rpc.(*Server).readRequest(0xc820458580, 0x7fa286946530, 0xc820493260, 0xc820458580, 0xc820491480, 0xc82008eb80, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/rpc/server.go:543 +0x8b
net/rpc.(*Server).ServeCodec(0xc820458580, 0x7fa286946530, 0xc820493260)
	/usr/local/go/src/net/rpc/server.go:462 +0x8c
github.com/derekparker/delve/service/rpc.(*ServerImpl).Run.func1(0xc8200260c8)
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/server.go:72 +0x4f9
created by github.com/derekparker/delve/service/rpc.(*ServerImpl).Run
	/usr/src/go/src/github.com/derekparker/delve/service/rpc/server.go:73 +0x122

goroutine 18 [IO wait]:
net.runtime_pollWait(0x7fa286939698, 0x72, 0xc82000c1b0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200159c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200159c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820015960, 0xc8207e8001, 0xdff, 0xdff, 0x0, 0x7fa286934050, 0xc82000c1b0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82010a050, 0xc8207e8001, 0xdff, 0xdff, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
encoding/json.(*Decoder).refill(0xc820496000, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc820496000, 0x1, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc820496000, 0x9669e0, 0xc820110148, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:57 +0x159
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc820110100, 0xc820494750, 0x0, 0x0)
	/usr/local/go/src/net/rpc/jsonrpc/client.go:75 +0x8f
net/rpc.(*Client).input(0xc820116120)
	/usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0xd2

goroutine 20 [chan receive]:
github.com/derekparker/delve/terminal.(*Term).Run.func1(0xc820116360, 0xc82020ad70)
	/usr/src/go/src/github.com/derekparker/delve/terminal/terminal.go:56 +0x77
created by github.com/derekparker/delve/terminal.(*Term).Run
	/usr/src/go/src/github.com/derekparker/delve/terminal/terminal.go:62 +0x1c2
```

### PR DESCRIPTION
**Pull request by aarzilli**
Fixes #414

### CODE REVIEW

**Comment by aarzilli** [comment]
@lukehoban if you can take a look at the windows failure, it shouldn't be too hard, it's just that `proc.(*Thread).stepInstruction` needs to notice when the process quits.

**Comment by lukehoban** [comment]
Sorry for the delay.

After some investigation, it looks like the only reliable fix for this is to ignore failures when calling `SuspendThread`, which seems to fail on some threads when the process is shutting down.  (I believe there are actually even more rare (and undocumented) cases where this will fail as well, so this is probably generally a safer thing to do).  

```diff
diff --git a/proc/threads_windows.go b/proc/threads_windows.go
index c82fc7b..4a20059 100644
--- a/proc/threads_windows.go
+++ b/proc/threads_windows.go
@@ -50,10 +50,7 @@ func (t *Thread) singleStep() error {
                if thread.ID == t.ID {
                        continue
                }
-               res := C.SuspendThread(C.HANDLE(thread.os.hThread))
-               if res == C.DWORD(0xFFFFFFFF) {
-                       return fmt.Errorf("could not suspend thread: %d", thread.ID)
-               }
+               _ = C.SuspendThread(C.HANDLE(thread.os.hThread))
        }

        // Continue and wait for the step to complete
@@ -73,10 +70,7 @@ func (t *Thread) singleStep() error {
                if thread.ID == t.ID {
                        continue
                }
-               res := C.ResumeThread(C.HANDLE(thread.os.hThread))
-               if res == C.DWORD(0xFFFFFFFF) {
-                       return fmt.Errorf("ould not resume thread: %d", thread.ID)
-               }
+               _ = C.ResumeThread(C.HANDLE(thread.os.hThread))
        }

        // Unset the processor TRAP flag

```

With that patch applied, I'm seeing tests pass cleanly.

Also - heads up that this patch will conflict with #425, but easy to fix up.

**Comment by aarzilli** [comment]
Is there no way at all to figure out that the process is shutting down and only ignore the errors then?

**Comment by lukehoban** [comment]
The failures from `SuspendThread` are being raised here before we are told that the threads are exiting. 

On the immediately ensuing `ContinueDebugEvent/WaitForDebugEvent` we get the thread exit events for each of the threads other than the one being stepped before getting the step event notification.

So if we want to be sure this is the reason for the failures, we could record each thread that failed to suspend, then remove from that list each thread that sends an exit event on the immediately following Continue, then raise the suspend failure errors for any threads that didn't exit.

It'll be a little messy, but I'm happy to add that logic on top of this PR as a separate change.  For now, you can either leave the Windows test failing, or apply the patch I shared and I'll add the error reporting in the common case back.

Note that I would not be surprised if we find additional undocumented reasons why `SuspendThread` can occasionally fail in the future.

**Comment by aarzilli** [comment]
Added @lukehoban's patch, rebased on master

**Comment by derekparker** [comment]
Merged, but @lukehoban, is there more work to be done (in another patch) to improve error handling here, are (in your opinion) are we fine to continue ignoring these errors (during single-stepping) on Windows?

**Pull request closed without merging**
