### PR TITLE
typo

### PR DESCRIPTION
**Pull request by custa**

### CODE REVIEW

**Comment by derekparker** [comment]
Thanks for this patch, however this file is generated. To properly update this file, please edit the description at `pkg/terminal/command.go` and then run `go run ./scripts/gen-cli-docs.go`.

**Comment by aarzilli** [comment]
@custa the script should work now.

**Comment by derekparker** [comment]
@custa ping.

**Comment by custa** [comment]
I will update this PR and #847 soon, please wait a moment
@aarzilli @derekparker

**Comment by custa** [comment]
After I fork and execute `go run ./scripts/gen-usage-docs.go`, there is some wrong, how can I resolve it, please help. @derekparker 

```
~/Codes/go/src/github.com/custa/delve (master) $ go run ./scripts/gen-usage-docs.go 
# command-line-arguments
scripts/gen-usage-docs.go:11: cannot use cmds.New() (type *"github.com/derekparker/delve/vendor/github.com/spf13/cobra".Command) as type *"github.com/custa/delve/vendor/github.com/spf13/cobra".Command in argument to doc.GenMarkdownTree
~/Codes/go/src/github.com/custa/delve (master) $ 
~/Codes/go/src/github.com/custa/delve (master) $ git log --oneline -1
d8bb8ed (HEAD -> master, upstream/master, patch-2) proc/variables: fill Len field of maps when recursion limit is reached (#834)
```

**Comment by aarzilli** [comment]
The way to contribute to a go project is to `go get` the original project, then use `git remote add`:
```
go get github.com/derekparker/delve/cmd/dlv
cd $GOPATH/src/github.com/derekparker/delve/
git remote add myfork git@github.com:custa/delve.git
```
Then push to `myfork`, if you `go get` your fork (like you are doing here) you will have problem with package paths.

**Pull request merged**
